
/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "flaianagpgAnagrafesedipgService",
                  wsdlLocation = "classpath:wsdl/flaianagpgAnagrafesedipg.wsdl",
                  targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
public class FlaianagpgAnagrafesedipgService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", "flaianagpgAnagrafesedipgService");
    public final static QName FlaianagpgAnagrafesedipg = new QName("http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", "flaianagpgAnagrafesedipg");
    static {
        URL url = FlaianagpgAnagrafesedipgService.class.getClassLoader().getResource("wsdl/flaianagpgAnagrafesedipg.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(FlaianagpgAnagrafesedipgService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/flaianagpgAnagrafesedipg.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FlaianagpgAnagrafesedipgService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FlaianagpgAnagrafesedipgService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlaianagpgAnagrafesedipgService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FlaianagpgAnagrafesedipgService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FlaianagpgAnagrafesedipgService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FlaianagpgAnagrafesedipgService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FlaianagpgAnagrafesedipg
     */
    @WebEndpoint(name = "flaianagpgAnagrafesedipg")
    public FlaianagpgAnagrafesedipg getFlaianagpgAnagrafesedipg() {
        return super.getPort(FlaianagpgAnagrafesedipg, FlaianagpgAnagrafesedipg.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlaianagpgAnagrafesedipg
     */
    @WebEndpoint(name = "flaianagpgAnagrafesedipg")
    public FlaianagpgAnagrafesedipg getFlaianagpgAnagrafesedipg(WebServiceFeature... features) {
        return super.getPort(FlaianagpgAnagrafesedipg, FlaianagpgAnagrafesedipg.class, features);
    }

}
