
/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", name = "flaianagpgAnagrafesedipg")
@XmlSeeAlso({ObjectFactory.class})
public interface FlaianagpgAnagrafesedipg {

    @WebMethod
    @RequestWrapper(localName = "getDettaglioSedePersonaGiuridica", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioSedePersonaGiuridica")
    @ResponseWrapper(localName = "getDettaglioSedePersonaGiuridicaResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioSedePersonaGiuridicaResponse")
    @WebResult(name = "getDettaglioSedePersonaGiuridicaReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultDettaglioSede getDettaglioSedePersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getBacino", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetBacino")
    @ResponseWrapper(localName = "getBacinoResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetBacinoResponse")
    @WebResult(name = "getBacinoReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultBacino getBacino(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException1, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioAreeTerritorialiPk", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioAreeTerritorialiPk")
    @ResponseWrapper(localName = "getDettaglioAreeTerritorialiPkResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioAreeTerritorialiPkResponse")
    @WebResult(name = "getDettaglioAreeTerritorialiPkReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultDettaglioAreeTerritoriali getDettaglioAreeTerritorialiPk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.RequestGetDettaglioAreeTerritoriali in0
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoSediPersonaGiuridica", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediPersonaGiuridica")
    @ResponseWrapper(localName = "getElencoSediPersonaGiuridicaResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediPersonaGiuridicaResponse")
    @WebResult(name = "getElencoSediPersonaGiuridicaReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultElencoSedi getElencoSediPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.util.List<java.lang.String> in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoSediOperatore", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOperatore")
    @ResponseWrapper(localName = "getElencoSediOperatoreResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOperatoreResponse")
    @WebResult(name = "getElencoSediOperatoreReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultElencoSedi getElencoSediOperatore(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.AkOperatore in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in4
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.TestResourcesResponse")
    @WebResult(name = "testResourcesReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public boolean testResources()
 throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioSedeOperatore", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioSedeOperatore")
    @ResponseWrapper(localName = "getDettaglioSedeOperatoreResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetDettaglioSedeOperatoreResponse")
    @WebResult(name = "getDettaglioSedeOperatoreReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultDettaglioSede getDettaglioSedeOperatore(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.AkOperatore in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoSediOccasionaliOperatore", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOccasionaliOperatore")
    @ResponseWrapper(localName = "getElencoSediOccasionaliOperatoreResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOccasionaliOperatoreResponse")
    @WebResult(name = "getElencoSediOccasionaliOperatoreReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultElencoSediOccasionali getElencoSediOccasionaliOperatore(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.AkOperatore in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoSediOccasionaliPersonaGiuridica", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOccasionaliPersonaGiuridica")
    @ResponseWrapper(localName = "getElencoSediOccasionaliPersonaGiuridicaResponse", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.GetElencoSediOccasionaliPersonaGiuridicaResponse")
    @WebResult(name = "getElencoSediOccasionaliPersonaGiuridicaReturn", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaianag.flaianagpgAnagrafesedi.ResultElencoSediOccasionali getElencoSediOccasionaliPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafesedipg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;
}
