
/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", name = "flaianagpgAnagrafepg")
@XmlSeeAlso({ObjectFactory.class})
public interface FlaianagpgAnagrafepg {

    @WebMethod
    @RequestWrapper(localName = "getElencoElementiPkV2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiPkV2")
    @ResponseWrapper(localName = "getElencoElementiPkV2Response", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiPkV2Response")
    @WebResult(name = "getElencoElementiPkV2Return", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoElementoDtoV2 getElencoElementiPkV2(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in6
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "eliminaElemento", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.EliminaElemento")
    @ResponseWrapper(localName = "eliminaElementoResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.EliminaElementoResponse")
    @WebResult(name = "eliminaElementoReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultEliminaElemento eliminaElemento(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioOperatore", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioOperatore")
    @ResponseWrapper(localName = "getDettaglioOperatoreResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioOperatoreResponse")
    @WebResult(name = "getDettaglioOperatoreReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioPersonaGiuridica getDettaglioOperatore(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.AkOperatore in1
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, MateriaNotYetSupportedException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getFunzioneOrganizzativa", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetFunzioneOrganizzativa")
    @ResponseWrapper(localName = "getFunzioneOrganizzativaResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetFunzioneOrganizzativaResponse")
    @WebResult(name = "getFunzioneOrganizzativaReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public java.util.List<it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.SelItemDto> getFunzioneOrganizzativa()
 throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoTipoElemento", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoTipoElemento")
    @ResponseWrapper(localName = "getElencoTipoElementoResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoTipoElementoResponse")
    @WebResult(name = "getElencoTipoElementoReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoTipoElementoDto getElencoTipoElemento(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestioneReferenteDDR", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneReferenteDDR")
    @ResponseWrapper(localName = "gestioneReferenteDDRResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneReferenteDDRResponse")
    @WebResult(name = "gestioneReferenteDDRReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultGestioneReferenteDDR gestioneReferenteDDR(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneReferenteDDRInput in0
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioPersonaGiuridica", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioPersonaGiuridica")
    @ResponseWrapper(localName = "getDettaglioPersonaGiuridicaResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioPersonaGiuridicaResponse")
    @WebResult(name = "getDettaglioPersonaGiuridicaReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioPersonaGiuridica getDettaglioPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        int in1
    ) throws TooManyOccurencesException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTipoGestioneFirma", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetTipoGestioneFirma")
    @ResponseWrapper(localName = "getTipoGestioneFirmaResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetTipoGestioneFirmaResponse")
    @WebResult(name = "getTipoGestioneFirmaReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public java.util.List<it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.SelItemDto> getTipoGestioneFirma()
 throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod(operationName = "getElencoPG_GCO")
    @RequestWrapper(localName = "getElencoPG_GCO", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoPGGCO")
    @ResponseWrapper(localName = "getElencoPG_GCOResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoPGGCOResponse")
    @WebResult(name = "getElencoPG_GCOReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoPG getElencoPGGCO(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.util.List<it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.AkOperatore> in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.util.List<java.lang.String> in2
    ) throws MateriaNotYetSupportedException_Exception, TooManyOccurencesException_Exception, SystemException_Exception, InvalidParameterException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoClassificazione", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoClassificazione")
    @ResponseWrapper(localName = "getElencoClassificazioneResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoClassificazioneResponse")
    @WebResult(name = "getElencoClassificazioneReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultClassifElementoArrayDto getElencoClassificazione(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        int in0
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "aggiornaElemento", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.AggiornaElemento")
    @ResponseWrapper(localName = "aggiornaElementoResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.AggiornaElementoResponse")
    @WebResult(name = "aggiornaElementoReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultAggiornaElemento aggiornaElemento(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.AggiornaElementoDto in0
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoElementiAk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiAk")
    @ResponseWrapper(localName = "getElencoElementiAkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiAkResponse")
    @WebResult(name = "getElencoElementiAkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoElementoDto getElencoElementiAk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in6,
        @WebParam(name = "in7", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in7
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciElemento", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.InserisciElemento")
    @ResponseWrapper(localName = "inserisciElementoResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.InserisciElementoResponse")
    @WebResult(name = "inserisciElementoReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultInserisciElemento inserisciElemento(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.InserisciElementoDto in0
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestioneFirmatario", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneFirmatario")
    @ResponseWrapper(localName = "gestioneFirmatarioResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneFirmatarioResponse")
    @WebResult(name = "gestioneFirmatarioReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneFirmatarioOutput gestioneFirmatario(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GestioneFirmatarioInput in0
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioElementiPkV2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiPkV2")
    @ResponseWrapper(localName = "getDettaglioElementiPkV2Response", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiPkV2Response")
    @WebResult(name = "getDettaglioElementiPkV2Return", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioElementoDtoV2 getDettaglioElementiPkV2(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoIncarichiPk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoIncarichiPk")
    @ResponseWrapper(localName = "getElencoIncarichiPkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoIncarichiPkResponse")
    @WebResult(name = "getElencoIncarichiPkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultGetElencoIncarichi getElencoIncarichiPk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in6
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoElementiEstesoAk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiEstesoAk")
    @ResponseWrapper(localName = "getElencoElementiEstesoAkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiEstesoAkResponse")
    @WebResult(name = "getElencoElementiEstesoAkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoElementoEstesoDto getElencoElementiEstesoAk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in6,
        @WebParam(name = "in7", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in7
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.TestResourcesResponse")
    @WebResult(name = "testResourcesReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public boolean testResources()
 throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDatiAteco2007", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDatiAteco2007")
    @ResponseWrapper(localName = "getDatiAteco2007Response", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDatiAteco2007Response")
    @WebResult(name = "getDatiAteco2007Return", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultAteco2007 getDatiAteco2007(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in2
    ) throws SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoPG", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoPG")
    @ResponseWrapper(localName = "getElencoPGResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoPGResponse")
    @WebResult(name = "getElencoPGReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoPG getElencoPG(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.util.List<java.lang.String> in7
    ) throws MateriaNotYetSupportedException_Exception, TooManyOccurencesException_Exception, SystemException_Exception, InvalidParameterException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioElementiAk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiAk")
    @ResponseWrapper(localName = "getDettaglioElementiAkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiAkResponse")
    @WebResult(name = "getDettaglioElementiAkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioElementoDto getDettaglioElementiAk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoElementiPk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiPk")
    @ResponseWrapper(localName = "getElencoElementiPkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiPkResponse")
    @WebResult(name = "getElencoElementiPkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoElementoDto getElencoElementiPk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in6
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoElementiEstesoPk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiEstesoPk")
    @ResponseWrapper(localName = "getElencoElementiEstesoPkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoElementiEstesoPkResponse")
    @WebResult(name = "getElencoElementiEstesoPkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultElencoElementoEstesoDto getElencoElementiEstesoPk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in6
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoCodiciSede", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoCodiciSede")
    @ResponseWrapper(localName = "getElencoCodiciSedeResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoCodiciSedeResponse")
    @WebResult(name = "getElencoCodiciSedeReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public java.util.List<java.lang.String> getElencoCodiciSede(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in3
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoDettaglioElementiAk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoDettaglioElementiAk")
    @ResponseWrapper(localName = "getElencoDettaglioElementiAkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoDettaglioElementiAkResponse")
    @WebResult(name = "getElencoDettaglioElementiAkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioElementiDto getElencoDettaglioElementiAk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.util.List<java.lang.String> in3
    ) throws MateriaNotSupportedByOperationException_Exception, MateriaNotYetSupportedException_Exception, AnagrafePgException_Exception, TooManyOccurencesException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoIncarichiAk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoIncarichiAk")
    @ResponseWrapper(localName = "getElencoIncarichiAkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetElencoIncarichiAkResponse")
    @WebResult(name = "getElencoIncarichiAkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultGetElencoIncarichi getElencoIncarichiAk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in2,
        @WebParam(name = "in3", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in3,
        @WebParam(name = "in4", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.String in7
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, AnagrafePgException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getApplicationMessage", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetApplicationMessage")
    @ResponseWrapper(localName = "getApplicationMessageResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetApplicationMessageResponse")
    @WebResult(name = "getApplicationMessageReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultMessage getApplicationMessage(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDettaglioElementiPk", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiPk")
    @ResponseWrapper(localName = "getDettaglioElementiPkResponse", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/", className = "it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.GetDettaglioElementiPkResponse")
    @WebResult(name = "getDettaglioElementiPkReturn", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
    public it.csi.serse.serseapi.integration.ws.cxf.flaianag.flaianagpgAnagrafepg.ResultDettaglioElementoDto getDettaglioElementiPk(

        @WebParam(name = "in0", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://anagrafepg.interfacecsi.flaianagpg.flaianag.csi.it/")
        java.lang.Integer in1
    ) throws MateriaNotSupportedByOperationException_Exception, AnagrafePgException_Exception, SystemException_Exception, CSIException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;
}
