package it.csi.serse.serseweb.integration.ws.cxf.flaidoor;

/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", name = "orchflaiFlaidoorsrv")
@XmlSeeAlso({ObjectFactory.class})
public interface OrchflaiFlaidoorsrv {

    @WebMethod
    @RequestWrapper(localName = "findRuoliForPersonaInApplication", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindRuoliForPersonaInApplication")
    @ResponseWrapper(localName = "findRuoliForPersonaInApplicationResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindRuoliForPersonaInApplicationResponse")
    @WebResult(name = "findRuoliForPersonaInApplicationReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Ruolo> findRuoliForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Application in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "selfCheck", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SelfCheck")
    @ResponseWrapper(localName = "selfCheckResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SelfCheckResponse")
    @WebResult(name = "selfCheckReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaidoor.InvocationNode selfCheck(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.CalledResource> in0
    ) throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInApplicationConcurrent", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInApplicationConcurrent")
    @ResponseWrapper(localName = "findActorsForPersonaInApplicationConcurrentResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInApplicationConcurrentResponse")
    @WebResult(name = "findActorsForPersonaInApplicationConcurrentReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Actor> findActorsForPersonaInApplicationConcurrent(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Application in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPersonaAutorizzataInUseCase", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsPersonaAutorizzataInUseCase")
    @ResponseWrapper(localName = "isPersonaAutorizzataInUseCaseResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsPersonaAutorizzataInUseCaseResponse")
    @WebResult(name = "isPersonaAutorizzataInUseCaseReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.Boolean isPersonaAutorizzataInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaCertificato", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaCertificato")
    @ResponseWrapper(localName = "identificaCertificatoResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaCertificatoResponse")
    @WebResult(name = "identificaCertificatoReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita identificaCertificato(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        byte[] in0
    ) throws InternalException_Exception, IdProviderNotFoundException_Exception, SystemException_Exception, CSIException_Exception, CertRevokedException_Exception, UnrecoverableException_Exception, CertOutsideValidityException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isIdentitaAutentica", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsIdentitaAutentica")
    @ResponseWrapper(localName = "isIdentitaAutenticaResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsIdentitaAutenticaResponse")
    @WebResult(name = "isIdentitaAutenticaReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.Boolean isIdentitaAutentica(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0
    ) throws SystemException_Exception, InternalException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findElencoMenuDiApplicativoForUtenteDelegato", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindElencoMenuDiApplicativoForUtenteDelegato")
    @ResponseWrapper(localName = "findElencoMenuDiApplicativoForUtenteDelegatoResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindElencoMenuDiApplicativoForUtenteDelegatoResponse")
    @WebResult(name = "findElencoMenuDiApplicativoForUtenteDelegatoReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.MenuDiApplicativo> findElencoMenuDiApplicativoForUtenteDelegato(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in2
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setElencoMessaggioComeNonLetti", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SetElencoMessaggioComeNonLetti")
    @ResponseWrapper(localName = "setElencoMessaggioComeNonLettiResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SetElencoMessaggioComeNonLettiResponse")
    public void setElencoMessaggioComeNonLetti(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.util.List<java.lang.String> in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessaggiBachecaByUtente", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetMessaggiBachecaByUtente")
    @ResponseWrapper(localName = "getMessaggiBachecaByUtenteResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetMessaggiBachecaByUtenteResponse")
    @WebResult(name = "getMessaggiBachecaByUtenteReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.MessaggioBacheca> getMessaggiBachecaByUtente(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.Integer in1,
        @WebParam(name = "in2", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in3
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findElencoMenuDiApplicativoForUtenteInRuolo", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindElencoMenuDiApplicativoForUtenteInRuolo")
    @ResponseWrapper(localName = "findElencoMenuDiApplicativoForUtenteInRuoloResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindElencoMenuDiApplicativoForUtenteInRuoloResponse")
    @WebResult(name = "findElencoMenuDiApplicativoForUtenteInRuoloReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.MenuDiApplicativo> findElencoMenuDiApplicativoForUtenteInRuolo(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in2
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInUseCase", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInUseCase")
    @ResponseWrapper(localName = "findActorsForPersonaInUseCaseResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInUseCaseResponse")
    @WebResult(name = "findActorsForPersonaInUseCaseReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Actor> findActorsForPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setElencoMessaggioComeLetti", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SetElencoMessaggioComeLetti")
    @ResponseWrapper(localName = "setElencoMessaggioComeLettiResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.SetElencoMessaggioComeLettiResponse")
    public void setElencoMessaggioComeLetti(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.util.List<java.lang.String> in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInApplication", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInApplication")
    @ResponseWrapper(localName = "findActorsForPersonaInApplicationResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInApplicationResponse")
    @WebResult(name = "findActorsForPersonaInApplicationReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Actor> findActorsForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Application in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getInfoPersonaInUseCaseConcurrent", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaInUseCaseConcurrent")
    @ResponseWrapper(localName = "getInfoPersonaInUseCaseConcurrentResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaInUseCaseConcurrentResponse")
    @WebResult(name = "getInfoPersonaInUseCaseConcurrentReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.String getInfoPersonaInUseCaseConcurrent(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getInfoPersonaInUseCase", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaInUseCase")
    @ResponseWrapper(localName = "getInfoPersonaInUseCaseResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaInUseCaseResponse")
    @WebResult(name = "getInfoPersonaInUseCaseReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.String getInfoPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findUseCasesForPersonaInApplication", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindUseCasesForPersonaInApplication")
    @ResponseWrapper(localName = "findUseCasesForPersonaInApplicationResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindUseCasesForPersonaInApplicationResponse")
    @WebResult(name = "findUseCasesForPersonaInApplicationReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase> findUseCasesForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Application in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getInfoPersonaSchema", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaSchema")
    @ResponseWrapper(localName = "getInfoPersonaSchemaResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.GetInfoPersonaSchemaResponse")
    @WebResult(name = "getInfoPersonaSchemaReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.String getInfoPersonaSchema(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Ruolo in0
    ) throws SystemException_Exception, InternalException_Exception, CSIException_Exception, UnrecoverableException_Exception, BadRuoloException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findMessaggioByCodApplicativo", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindMessaggioByCodApplicativo")
    @ResponseWrapper(localName = "findMessaggioByCodApplicativoResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindMessaggioByCodApplicativoResponse")
    @WebResult(name = "findMessaggioByCodApplicativoReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.String findMessaggioByCodApplicativo(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPersonaInRuolo", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsPersonaInRuolo")
    @ResponseWrapper(localName = "isPersonaInRuoloResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IsPersonaInRuoloResponse")
    @WebResult(name = "isPersonaInRuoloReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.lang.Boolean isPersonaInRuolo(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Ruolo in1
    ) throws InternalException_Exception, BadRuoloException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "hasSelfCheck", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.HasSelfCheck")
    @ResponseWrapper(localName = "hasSelfCheckResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.HasSelfCheckResponse")
    @WebResult(name = "hasSelfCheckReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public boolean hasSelfCheck()
 throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaUserPasswordPIN", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaUserPasswordPIN")
    @ResponseWrapper(localName = "identificaUserPasswordPINResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaUserPasswordPINResponse")
    @WebResult(name = "identificaUserPasswordPINReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita identificaUserPasswordPIN(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in2
    ) throws InternalException_Exception, AuthException_Exception, MalformedUsernameException_Exception, IdProviderNotFoundException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.TestResourcesResponse")
    @WebResult(name = "testResourcesReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public boolean testResources()
 throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findUseCasesForPersonaRoleInApplication", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindUseCasesForPersonaRoleInApplication")
    @ResponseWrapper(localName = "findUseCasesForPersonaRoleInApplicationResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindUseCasesForPersonaRoleInApplicationResponse")
    @WebResult(name = "findUseCasesForPersonaRoleInApplicationReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase> findUseCasesForPersonaRoleInApplication(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in2
    ) throws InternalException_Exception, BadRuoloException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInUseCaseConcurrent", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInUseCaseConcurrent")
    @ResponseWrapper(localName = "findActorsForPersonaInUseCaseConcurrentResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindActorsForPersonaInUseCaseConcurrentResponse")
    @WebResult(name = "findActorsForPersonaInUseCaseConcurrentReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Actor> findActorsForPersonaInUseCaseConcurrent(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaUserPassword", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaUserPassword")
    @ResponseWrapper(localName = "identificaUserPasswordResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.IdentificaUserPasswordResponse")
    @WebResult(name = "identificaUserPasswordReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita identificaUserPassword(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        java.lang.String in1
    ) throws InternalException_Exception, AuthException_Exception, MalformedUsernameException_Exception, IdProviderNotFoundException_Exception, SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findRuoliForPersonaInUseCase", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindRuoliForPersonaInUseCase")
    @ResponseWrapper(localName = "findRuoliForPersonaInUseCaseResponse", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.flaidoor.FindRuoliForPersonaInUseCaseResponse")
    @WebResult(name = "findRuoliForPersonaInUseCaseReturn", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Ruolo> findRuoliForPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
        it.csi.serse.serseweb.integration.ws.cxf.flaidoor.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, SystemException_Exception, NoSuchUseCaseException_Exception, CSIException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;
}
