package it.csi.serse.serseweb.integration.ws.cxf.flaidoor;

/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "orchflaiFlaidoorsrvService",
                  wsdlLocation = "classpath:wsdl/orchflaiFlaidoorsrv.wsdl",
                  targetNamespace = "http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/")
public class OrchflaiFlaidoorsrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", "orchflaiFlaidoorsrvService");
    public final static QName OrchflaiFlaidoorsrv = new QName("http://flaidoorsrv.interfacecsi.orchflai.flaidoor.csi.it/", "orchflaiFlaidoorsrv");
    static {
        URL url = OrchflaiFlaidoorsrvService.class.getClassLoader().getResource("wsdl/orchflaiFlaidoorsrv.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(OrchflaiFlaidoorsrvService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/orchflaiFlaidoorsrv.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrchflaiFlaidoorsrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrchflaiFlaidoorsrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrchflaiFlaidoorsrvService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrchflaiFlaidoorsrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrchflaiFlaidoorsrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrchflaiFlaidoorsrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrchflaiFlaidoorsrv
     */
    @WebEndpoint(name = "orchflaiFlaidoorsrv")
    public OrchflaiFlaidoorsrv getOrchflaiFlaidoorsrv() {
        return super.getPort(OrchflaiFlaidoorsrv, OrchflaiFlaidoorsrv.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrchflaiFlaidoorsrv
     */
    @WebEndpoint(name = "orchflaiFlaidoorsrv")
    public OrchflaiFlaidoorsrv getOrchflaiFlaidoorsrv(WebServiceFeature... features) {
        return super.getPort(OrchflaiFlaidoorsrv, OrchflaiFlaidoorsrv.class, features);
    }

}
