package it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb;

/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", name = "Operscambserv")
@XmlSeeAlso({ObjectFactory.class})
public interface Operscambserv {

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieConcludiServizioSerse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiServizioSerse")
    @ResponseWrapper(localName = "gestInterscMaterieConcludiServizioSerseResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiServizioSerseResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiServizioSerseOutput gestInterscMaterieConcludiServizioSerse(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiServizioSerseInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetDatiDemaConv", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDatiDemaConv")
    @ResponseWrapper(localName = "gestInterscMaterieGetDatiDemaConvResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDatiDemaConvResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDatiDemaConvOutput gestInterscMaterieGetDatiDemaConv(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDatiDemaConvInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSearchUC", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUC")
    @ResponseWrapper(localName = "gestInterscMaterieSearchUCResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCOutput gestInterscMaterieSearchUC(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "bonifica", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.Bonifica")
    @ResponseWrapper(localName = "bonificaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.BonificaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<java.lang.String> bonifica(

        @WebParam(name = "listId", targetNamespace = "")
        java.util.List<java.lang.Long> listId
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaGetAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetAttivita")
    @ResponseWrapper(localName = "gestAttivitaGetAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetAttivitaOutput gestAttivitaGetAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieCalcolaVoucher", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcolaVoucher")
    @ResponseWrapper(localName = "gestInterscMaterieCalcolaVoucherResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcolaVoucherResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcolaVoucherOutput gestInterscMaterieCalcolaVoucher(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcolaVoucherInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verificaBudget", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudget")
    @ResponseWrapper(localName = "verificaBudgetResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetOutput verificaBudget(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttoLiqSearchImportiLiquidQP", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidQP")
    @ResponseWrapper(localName = "gestAttoLiqSearchImportiLiquidQPResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidQPResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidQPOutput> gestAttoLiqSearchImportiLiquidQP(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidQPInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieFinDirettoIstanzaAttivitaRep", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieFinDirettoIstanzaAttivitaRep")
    @ResponseWrapper(localName = "gestInterscMaterieFinDirettoIstanzaAttivitaRepResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieFinDirettoIstanzaAttivitaRepResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieFinDirettoIstanzaAttivitaRepOutput gestInterscMaterieFinDirettoIstanzaAttivitaRep(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieFinDirettoIstanzaAttivitaRepInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetBDGTDisponibileSF", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBDGTDisponibileSF")
    @ResponseWrapper(localName = "gestInterscMaterieGetBDGTDisponibileSFResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBDGTDisponibileSFResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBDGTDisponibileSFOutput gestInterscMaterieGetBDGTDisponibileSF(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBDGTDisponibileSFInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttoLiqSearchImportiLiquidazioniRate", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidazioniRate")
    @ResponseWrapper(localName = "gestAttoLiqSearchImportiLiquidazioniRateResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidazioniRateResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidazioniRateOutput gestAttoLiqSearchImportiLiquidazioniRate(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttoLiqSearchImportiLiquidazioniRateInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchImportoFontiV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiV2")
    @ResponseWrapper(localName = "gestAttivitaSearchImportoFontiV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiOutputV2 gestAttivitaSearchImportoFontiV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, TooManyInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieCalcPreventivoSerse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcPreventivoSerse")
    @ResponseWrapper(localName = "gestInterscMaterieCalcPreventivoSerseResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcPreventivoSerseResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcPreventivoSerseOutput gestInterscMaterieCalcPreventivoSerse(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalcPreventivoSerseInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetBudgetDisponibileV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileV2")
    @ResponseWrapper(localName = "gestInterscMaterieGetBudgetDisponibileV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileOutputV2 gestInterscMaterieGetBudgetDisponibileV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileInputV2 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieCalPreventivoIstanzaCatalogo", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalPreventivoIstanzaCatalogo")
    @ResponseWrapper(localName = "gestInterscMaterieCalPreventivoIstanzaCatalogoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalPreventivoIstanzaCatalogoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalPreventivoIstanzaCatalogoOutput gestInterscMaterieCalPreventivoIstanzaCatalogo(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCalPreventivoIstanzaCatalogoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSearchUCdiOperazione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCdiOperazione")
    @ResponseWrapper(localName = "gestInterscMaterieSearchUCdiOperazioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCdiOperazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCdiOperazioneOutput gestInterscMaterieSearchUCdiOperazione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchUCdiOperazioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSoppressioneEdizione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneEdizione")
    @ResponseWrapper(localName = "gestInterscMaterieSoppressioneEdizioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneEdizioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneEdizioneOutput gestInterscMaterieSoppressioneEdizione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneEdizioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieRiapriIncontroDiServizio", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiapriIncontroDiServizio")
    @ResponseWrapper(localName = "gestInterscMaterieRiapriIncontroDiServizioResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiapriIncontroDiServizioResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiapriIncontroDiServizioOutput gestInterscMaterieRiapriIncontroDiServizio(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiapriIncontroDiServizioInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TestResourcesResponse")
    @WebResult(name = "result", targetNamespace = "")
    public boolean testResources(

        @WebParam(name = "dummy", targetNamespace = "")
        java.lang.String dummy
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieModificaServizioSerse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieModificaServizioSerse")
    @ResponseWrapper(localName = "gestInterscMaterieModificaServizioSerseResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieModificaServizioSerseResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieModificaServizioSerseOutput gestInterscMaterieModificaServizioSerse(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieModificaServizioSerseInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieAvviaEdizione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizione")
    @ResponseWrapper(localName = "gestInterscMaterieAvviaEdizioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneOutput gestInterscMaterieAvviaEdizione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "erogazioneAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivita")
    @ResponseWrapper(localName = "erogazioneAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaOutput erogazioneAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetBudgetDisponibile", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibile")
    @ResponseWrapper(localName = "gestInterscMaterieGetBudgetDisponibileResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileOutput gestInterscMaterieGetBudgetDisponibile(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetBudgetDisponibileInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieRitiraAllievo", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievo")
    @ResponseWrapper(localName = "gestInterscMaterieRitiraAllievoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoOutput gestInterscMaterieRitiraAllievo(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieExcelSubCampioneOPEAttuazione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEAttuazione")
    @ResponseWrapper(localName = "gestInterscMaterieExcelSubCampioneOPEAttuazioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEAttuazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEAttuazioneOutput gestInterscMaterieExcelSubCampioneOPEAttuazione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEAttuazioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaGetClassificFromIdAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetClassificFromIdAttivita")
    @ResponseWrapper(localName = "gestAttivitaGetClassificFromIdAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetClassificFromIdAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetClassificFromIdAttivitaOutput gestAttivitaGetClassificFromIdAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetClassificFromIdAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetEsitoIstanzaCatalogo", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoIstanzaCatalogo")
    @ResponseWrapper(localName = "gestInterscMaterieGetEsitoIstanzaCatalogoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoIstanzaCatalogoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoIstanzaCatalogoOutput gestInterscMaterieGetEsitoIstanzaCatalogo(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoIstanzaCatalogoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaInsertAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivita")
    @ResponseWrapper(localName = "gestAttivitaInsertAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaOutput gestAttivitaInsertAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchAttivita")
    @ResponseWrapper(localName = "gestAttivitaSearchAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchAttivitaOutput gestAttivitaSearchAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieCancellaVoucher", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCancellaVoucher")
    @ResponseWrapper(localName = "gestInterscMaterieCancellaVoucherResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCancellaVoucherResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCancellaVoucherOutput gestInterscMaterieCancellaVoucher(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCancellaVoucherInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSearchCodaDaElaborare", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchCodaDaElaborare")
    @ResponseWrapper(localName = "gestInterscMaterieSearchCodaDaElaborareResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchCodaDaElaborareResponse")
    public void gestInterscMaterieSearchCodaDaElaborare(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchCodaDaElaborareInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestServTecGestFasciaSearch", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestServTecGestFasciaSearch")
    @ResponseWrapper(localName = "gestServTecGestFasciaSearchResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestServTecGestFasciaSearchResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestServTecGestFasciaSearchOutput gestServTecGestFasciaSearch(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestServTecGestFasciaSearchInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestOperscambTabFinUpdateStato", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestOperscambTabFinUpdateStato")
    @ResponseWrapper(localName = "gestOperscambTabFinUpdateStatoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestOperscambTabFinUpdateStatoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestOperscambTabFinUpdateStatoOutput gestOperscambTabFinUpdateStato(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestOperscambTabFinUpdateStatoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieNuovoServizioSerse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoServizioSerse")
    @ResponseWrapper(localName = "gestInterscMaterieNuovoServizioSerseResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoServizioSerseResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoServizioSerseOutput gestInterscMaterieNuovoServizioSerse(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoServizioSerseInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieElencoBuoniAutNonInEdizione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizione")
    @ResponseWrapper(localName = "gestInterscMaterieElencoBuoniAutNonInEdizioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneOutput gestInterscMaterieElencoBuoniAutNonInEdizione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieExcelSubCampioneOPEGestione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEGestione")
    @ResponseWrapper(localName = "gestInterscMaterieExcelSubCampioneOPEGestioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEGestioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEGestioneOutput gestInterscMaterieExcelSubCampioneOPEGestione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieExcelSubCampioneOPEGestioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verificaBudgetImpegnoConsumo", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetImpegnoConsumo")
    @ResponseWrapper(localName = "verificaBudgetImpegnoConsumoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetImpegnoConsumoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetImpegnoConsumoOutput verificaBudgetImpegnoConsumo(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.VerificaBudgetImpegnoConsumoInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieRiempiOperCatalogoFinDiretto", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiempiOperCatalogoFinDiretto")
    @ResponseWrapper(localName = "gestInterscMaterieRiempiOperCatalogoFinDirettoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiempiOperCatalogoFinDirettoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiempiOperCatalogoFinDirettoOutput gestInterscMaterieRiempiOperCatalogoFinDiretto(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRiempiOperCatalogoFinDirettoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAsyncResult", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GetAsyncResult")
    @ResponseWrapper(localName = "getAsyncResultResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GetAsyncResultResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GetAsyncResultOutput getAsyncResult(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GetAsyncResultInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaDeleteAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaDeleteAttivita")
    @ResponseWrapper(localName = "gestAttivitaDeleteAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaDeleteAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaDeleteAttivitaOutput gestAttivitaDeleteAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaDeleteAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchDestinatariAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDestinatariAttivita")
    @ResponseWrapper(localName = "gestAttivitaSearchDestinatariAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDestinatariAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDestinatariAttivitaOutput gestAttivitaSearchDestinatariAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDestinatariAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAutorizzazioneSearchChiave", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAutorizzazioneSearchChiave")
    @ResponseWrapper(localName = "gestAutorizzazioneSearchChiaveResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAutorizzazioneSearchChiaveResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAutorizzazioneSearchChiaveOutput gestAutorizzazioneSearchChiave(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAutorizzazioneSearchChiaveInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieBuonoPersonaInSostituzione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieBuonoPersonaInSostituzione")
    @ResponseWrapper(localName = "gestInterscMaterieBuonoPersonaInSostituzioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieBuonoPersonaInSostituzioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieBuonoPersonaInSostituzioneOutput gestInterscMaterieBuonoPersonaInSostituzione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieBuonoPersonaInSostituzioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieConcludiEdizione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizione")
    @ResponseWrapper(localName = "gestInterscMaterieConcludiEdizioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneOutput gestInterscMaterieConcludiEdizione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieConcludiEdizioneV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneV2")
    @ResponseWrapper(localName = "gestInterscMaterieConcludiEdizioneV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneOutput gestInterscMaterieConcludiEdizioneV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneInputV2 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieConcludiEdizioneV3", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneV3")
    @ResponseWrapper(localName = "gestInterscMaterieConcludiEdizioneV3Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneV3Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneOutputV2 gestInterscMaterieConcludiEdizioneV3(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieConcludiEdizioneInputV3 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchImportoFonti", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFonti")
    @ResponseWrapper(localName = "gestAttivitaSearchImportoFontiResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiOutput gestAttivitaSearchImportoFonti(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchImportoFontiInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, TooManyInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieQuadroEconomicoDomanda", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieQuadroEconomicoDomanda")
    @ResponseWrapper(localName = "gestInterscMaterieQuadroEconomicoDomandaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieQuadroEconomicoDomandaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieQuadroEconomicoDomandaOutput gestInterscMaterieQuadroEconomicoDomanda(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieQuadroEconomicoDomandaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetEsitoServizioAsync", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoServizioAsync")
    @ResponseWrapper(localName = "gestInterscMaterieGetEsitoServizioAsyncResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoServizioAsyncResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoServizioAsyncOutput gestInterscMaterieGetEsitoServizioAsync(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetEsitoServizioAsyncInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieInsOperazioniIstanzaCatalogoAsync", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieInsOperazioniIstanzaCatalogoAsync")
    @ResponseWrapper(localName = "gestInterscMaterieInsOperazioniIstanzaCatalogoAsyncResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieInsOperazioniIstanzaCatalogoAsyncResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieInsOperazioniIstanzaCatalogoOutput gestInterscMaterieInsOperazioniIstanzaCatalogoAsync(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieInsOperazioniIstanzaCatalogoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieIscriviAllievoAEdizioneAvviata", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieIscriviAllievoAEdizioneAvviata")
    @ResponseWrapper(localName = "gestInterscMaterieIscriviAllievoAEdizioneAvviataResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieIscriviAllievoAEdizioneAvviataResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieIscriviAllievoAEdizioneAvviataOutput gestInterscMaterieIscriviAllievoAEdizioneAvviata(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieIscriviAllievoAEdizioneAvviataInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchDettagliAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDettagliAttivita")
    @ResponseWrapper(localName = "gestAttivitaSearchDettagliAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDettagliAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDettagliAttivitaOutput gestAttivitaSearchDettagliAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchDettagliAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaTerminaAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaTerminaAttivita")
    @ResponseWrapper(localName = "gestAttivitaTerminaAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaTerminaAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaTerminaAttivitaOutput gestAttivitaTerminaAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaTerminaAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetDataApprovCampione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDataApprovCampione")
    @ResponseWrapper(localName = "gestInterscMaterieGetDataApprovCampioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDataApprovCampioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDataApprovCampioneOutput gestInterscMaterieGetDataApprovCampione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetDataApprovCampioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSearchClassiTabFin", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchClassiTabFin")
    @ResponseWrapper(localName = "gestInterscMaterieSearchClassiTabFinResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchClassiTabFinResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchClassiTabFinOutput gestInterscMaterieSearchClassiTabFin(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchClassiTabFinInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestRataSearchDettagliRateSF", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestRataSearchDettagliRateSF")
    @ResponseWrapper(localName = "gestRataSearchDettagliRateSFResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestRataSearchDettagliRateSFResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestRataSearchDettagliRateSFOutput gestRataSearchDettagliRateSF(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestRataSearchDettagliRateSFInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieElencoBuoniAutorizzazione", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazione")
    @ResponseWrapper(localName = "gestInterscMaterieElencoBuoniAutorizzazioneResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneOutput gestInterscMaterieElencoBuoniAutorizzazione(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieAvviaEdizioneV3", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneV3")
    @ResponseWrapper(localName = "gestInterscMaterieAvviaEdizioneV3Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneV3Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneOutput gestInterscMaterieAvviaEdizioneV3(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneInputV3 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieAvviaEdizioneV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneV2")
    @ResponseWrapper(localName = "gestInterscMaterieAvviaEdizioneV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneOutput gestInterscMaterieAvviaEdizioneV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAvviaEdizioneInputV2 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieAssegnaVoucher", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAssegnaVoucher")
    @ResponseWrapper(localName = "gestInterscMaterieAssegnaVoucherResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAssegnaVoucherResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAssegnaVoucherOutput gestInterscMaterieAssegnaVoucher(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieAssegnaVoucherInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieEliminaServizioIncontri", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieEliminaServizioIncontri")
    @ResponseWrapper(localName = "gestInterscMaterieEliminaServizioIncontriResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieEliminaServizioIncontriResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieEliminaServizioIncontriOutput gestInterscMaterieEliminaServizioIncontri(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieEliminaServizioIncontriInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieRitiraAllievoV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoV2")
    @ResponseWrapper(localName = "gestInterscMaterieRitiraAllievoV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoV2Output gestInterscMaterieRitiraAllievoV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieRitiraAllievoV2Input input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetFlagPresenzaRev", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetFlagPresenzaRev")
    @ResponseWrapper(localName = "gestInterscMaterieGetFlagPresenzaRevResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetFlagPresenzaRevResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetFlagPresenzaRevOutput gestInterscMaterieGetFlagPresenzaRev(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetFlagPresenzaRevInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetInfoIstanzaCatalogo", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetInfoIstanzaCatalogo")
    @ResponseWrapper(localName = "gestInterscMaterieGetInfoIstanzaCatalogoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetInfoIstanzaCatalogoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetInfoIstanzaCatalogoOutput gestInterscMaterieGetInfoIstanzaCatalogo(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetInfoIstanzaCatalogoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception, TooManyInputException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieGetPraticaDomandaSoggFin", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetPraticaDomandaSoggFin")
    @ResponseWrapper(localName = "gestInterscMaterieGetPraticaDomandaSoggFinResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetPraticaDomandaSoggFinResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetPraticaDomandaSoggFinOutput gestInterscMaterieGetPraticaDomandaSoggFin(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieGetPraticaDomandaSoggFinInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieElencoBuoniAutNonInEdizioneV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneV2")
    @ResponseWrapper(localName = "gestInterscMaterieElencoBuoniAutNonInEdizioneV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneV2Output gestInterscMaterieElencoBuoniAutNonInEdizioneV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutNonInEdizioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaGetValEco", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetValEco")
    @ResponseWrapper(localName = "gestAttivitaGetValEcoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetValEcoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetValEcoOutput gestAttivitaGetValEco(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetValEcoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSearchFontiTabFin", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchFontiTabFin")
    @ResponseWrapper(localName = "gestInterscMaterieSearchFontiTabFinResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchFontiTabFinResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchFontiTabFinOutput gestInterscMaterieSearchFontiTabFin(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSearchFontiTabFinInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieSoppressioneBuonoPersona", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneBuonoPersona")
    @ResponseWrapper(localName = "gestInterscMaterieSoppressioneBuonoPersonaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneBuonoPersonaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneBuonoPersonaOutput gestInterscMaterieSoppressioneBuonoPersona(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieSoppressioneBuonoPersonaInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestTabFinSearch", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestTabFinSearch")
    @ResponseWrapper(localName = "gestTabFinSearchResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestTabFinSearchResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestTabFinSearchOutput gestTabFinSearch(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestTabFinSearchInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaCancellaErogazioneAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaCancellaErogazioneAttivita")
    @ResponseWrapper(localName = "gestAttivitaCancellaErogazioneAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaCancellaErogazioneAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaOutput gestAttivitaCancellaErogazioneAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaGetDatoEconomico", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetDatoEconomico")
    @ResponseWrapper(localName = "gestAttivitaGetDatoEconomicoResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetDatoEconomicoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetDatoEconomicoOutput gestAttivitaGetDatoEconomico(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaGetDatoEconomicoInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieCampionamento2127", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCampionamento2127")
    @ResponseWrapper(localName = "gestInterscMaterieCampionamento2127Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCampionamento2127Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCampionamento2127Output gestInterscMaterieCampionamento2127(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieCampionamento2127Input input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "processAsync", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ProcessAsync")
    @ResponseWrapper(localName = "processAsyncResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ProcessAsyncResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ProcessAsyncOutput processAsync(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ProcessAsyncInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaInsertAttivitaV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaV2")
    @ResponseWrapper(localName = "gestAttivitaInsertAttivitaV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaOutput gestAttivitaInsertAttivitaV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaInputV2 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaInsertOreErogateAttivita", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertOreErogateAttivita")
    @ResponseWrapper(localName = "gestAttivitaInsertOreErogateAttivitaResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertOreErogateAttivitaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaOutput gestAttivitaInsertOreErogateAttivita(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.ErogazioneAttivitaInput input
    ) throws Exception_Exception, OperScambServException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaSearchCommittenti", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchCommittenti")
    @ResponseWrapper(localName = "gestAttivitaSearchCommittentiResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchCommittentiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchCommittentiOutput gestAttivitaSearchCommittenti(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaSearchCommittentiInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestAttivitaInsertAttivitaV3", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaV3")
    @ResponseWrapper(localName = "gestAttivitaInsertAttivitaV3Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaV3Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaOutput gestAttivitaInsertAttivitaV3(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestAttivitaInsertAttivitaInputV3 input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieNuovoIncontroSrvSerse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoIncontroSrvSerse")
    @ResponseWrapper(localName = "gestInterscMaterieNuovoIncontroSrvSerseResponse", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoIncontroSrvSerseResponse")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoIncontroSrvSerseOutput gestInterscMaterieNuovoIncontroSrvSerse(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieNuovoIncontroSrvSerseInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "gestInterscMaterieElencoBuoniAutorizzazioneV2", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneV2")
    @ResponseWrapper(localName = "gestInterscMaterieElencoBuoniAutorizzazioneV2Response", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneV2Response")
    @WebResult(name = "result", targetNamespace = "")
    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneV2Output gestInterscMaterieElencoBuoniAutorizzazioneV2(

        @WebParam(name = "input", targetNamespace = "")
        it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.GestInterscMaterieElencoBuoniAutorizzazioneInput input
    ) throws Exception_Exception, OperScambServException_Exception, InvalidParameterException_Exception, UnrecoverableException_Exception;
}
