
package it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb;

/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 */

@WebFault(name = "TooManyInputException", targetNamespace = "http://operscambserv.interfacews.operserv.gamopera.csi.it/")
public class TooManyInputException_Exception extends java.lang.Exception {

    private it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TooManyInputException faultInfo;

    public TooManyInputException_Exception() {
        super();
    }

    public TooManyInputException_Exception(String message) {
        super(message);
    }

    public TooManyInputException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TooManyInputException_Exception(String message, it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TooManyInputException tooManyInputException) {
        super(message);
        this.faultInfo = tooManyInputException;
    }

    public TooManyInputException_Exception(String message, it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TooManyInputException tooManyInputException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = tooManyInputException;
    }

    public it.csi.serse.serseweb.integration.ws.cxf.gamopera.operscamb.TooManyInputException getFaultInfo() {
        return this.faultInfo;
    }
}
