/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * SERSE WEB API
 * API serse per applicazione
 *
 * OpenAPI spec version: 2.0.0
 * Contact: piergiorgio.chiriotti@consulenti.csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Questo serve solo per referenza, non serve implementarli tutti
 */
export interface CriterioFull { 
    /**
     * Equals
     */
    eq?: string;
    /**
     * Not equals
     */
    ne?: string;
    /**
     * Less than
     */
    lt?: string;
    /**
     * Less than or equal
     */
    lte?: string;
    /**
     * Greater than
     */
    gt?: string;
    /**
     * Greater than or equal
     */
    gte?: string;
    /**
     * In
     */
    _in?: Array<string>;
    /**
     * Not in
     */
    nin?: Array<string>;
    /**
     * Contains
     */
    c?: string;
    /**
     * Contains, ignore case
     */
    ci?: string;
    /**
     * Starts with
     */
    s?: string;
    /**
     * Starts with, ignore case
     */
    si?: string;
    /**
     * Ends with
     */
    e?: string;
    /**
     * Ends with, ignore case
     */
    ei?: string;
}