package it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common;

/*-
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", name = "budgetbilservCommon")
@XmlSeeAlso({ObjectFactory.class})
public interface BudgetbilservCommon {

    @WebMethod
    @RequestWrapper(localName = "searchGestFonteOI", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonteOI")
    @ResponseWrapper(localName = "searchGestFonteOIResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonteOIResponse")
    @WebResult(name = "searchGestFonteOIReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestFonteOI(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchAllAmmResponsabili", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAllAmmResponsabili")
    @ResponseWrapper(localName = "searchAllAmmResponsabiliResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAllAmmResponsabiliResponse")
    @WebResult(name = "searchAllAmmResponsabiliReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.AmmResponsabileDto> searchAllAmmResponsabili(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchOriginiFonti", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchOriginiFonti")
    @ResponseWrapper(localName = "searchOriginiFontiResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchOriginiFontiResponse")
    @WebResult(name = "searchOriginiFontiReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchOriginiFonti(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestMotAssCig", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestMotAssCig")
    @ResponseWrapper(localName = "searchGestMotAssCigResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestMotAssCigResponse")
    @WebResult(name = "searchGestMotAssCigReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestMotAssCig(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipolDocumenti", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipolDocumenti")
    @ResponseWrapper(localName = "searchGestTipolDocumentiResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipolDocumentiResponse")
    @WebResult(name = "searchGestTipolDocumentiReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipolDocumenti()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoObiettiviByRegolamento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoObiettiviByRegolamento")
    @ResponseWrapper(localName = "getElencoObiettiviByRegolamentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoObiettiviByRegolamentoResponse")
    @WebResult(name = "getElencoObiettiviByRegolamentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoObiettiviByRegolamento(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipoDetermina", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoDetermina")
    @ResponseWrapper(localName = "searchGestTipoDeterminaResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoDeterminaResponse")
    @WebResult(name = "searchGestTipoDeterminaReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipoDetermina()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestFonteByFonte", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonteByFonte")
    @ResponseWrapper(localName = "searchGestFonteByFonteResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonteByFonteResponse")
    @WebResult(name = "searchGestFonteByFonteReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestFonteByFonte(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchClassificazioniGAM", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchClassificazioniGAM")
    @ResponseWrapper(localName = "searchClassificazioniGAMResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchClassificazioniGAMResponse")
    @WebResult(name = "searchClassificazioniGAMReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchClassificazioniGAM(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in3
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchTipiAttiAmm", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchTipiAttiAmm")
    @ResponseWrapper(localName = "searchTipiAttiAmmResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchTipiAttiAmmResponse")
    @WebResult(name = "searchTipiAttiAmmReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchTipiAttiAmm(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestOrigini", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestOrigini")
    @ResponseWrapper(localName = "searchGestOriginiResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestOriginiResponse")
    @WebResult(name = "searchGestOriginiReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestOrigini()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestCicliFin", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestCicliFin")
    @ResponseWrapper(localName = "searchGestCicliFinResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestCicliFinResponse")
    @WebResult(name = "searchGestCicliFinReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestCicliFin(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoTipologieSpesa", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipologieSpesa")
    @ResponseWrapper(localName = "getElencoTipologieSpesaResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipologieSpesaResponse")
    @WebResult(name = "getElencoTipologieSpesaReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoTipologieSpesa()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoRegolamentiByTipoProcedimento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoRegolamentiByTipoProcedimento")
    @ResponseWrapper(localName = "getElencoRegolamentiByTipoProcedimentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoRegolamentiByTipoProcedimentoResponse")
    @WebResult(name = "getElencoRegolamentiByTipoProcedimentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoRegolamentiByTipoProcedimento(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoSettoriByTipoProcedimentoCodRegolamento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoSettoriByTipoProcedimentoCodRegolamento")
    @ResponseWrapper(localName = "getElencoSettoriByTipoProcedimentoCodRegolamentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoSettoriByTipoProcedimentoCodRegolamentoResponse")
    @WebResult(name = "getElencoSettoriByTipoProcedimentoCodRegolamentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoSettoriByTipoProcedimentoCodRegolamento(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPrimaryKey", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetPrimaryKey")
    @ResponseWrapper(localName = "getPrimaryKeyResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetPrimaryKeyResponse")
    @WebResult(name = "getPrimaryKeyReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.lang.Long getPrimaryKey(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchAzioniGAM", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAzioniGAM")
    @ResponseWrapper(localName = "searchAzioniGAMResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAzioniGAMResponse")
    @WebResult(name = "searchAzioniGAMReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.AzioniGamDto> searchAzioniGAM(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in4
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getLivelliGestProgrammazione", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetLivelliGestProgrammazione")
    @ResponseWrapper(localName = "getLivelliGestProgrammazioneResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetLivelliGestProgrammazioneResponse")
    @WebResult(name = "getLivelliGestProgrammazioneReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.LivelloClassificazionePOR> getLivelliGestProgrammazione(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestFonte", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonte")
    @ResponseWrapper(localName = "searchGestFonteResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestFonteResponse")
    @WebResult(name = "searchGestFonteReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestFonte(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipiAzioni", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipiAzioni")
    @ResponseWrapper(localName = "searchGestTipiAzioniResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipiAzioniResponse")
    @WebResult(name = "searchGestTipiAzioniReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipiAzioni()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoTipiProcedimento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiProcedimento")
    @ResponseWrapper(localName = "getElencoTipiProcedimentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiProcedimentoResponse")
    @WebResult(name = "getElencoTipiProcedimentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoTipiProcedimento()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "infoBilancioGestAmmResp", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.InfoBilancioGestAmmResp")
    @ResponseWrapper(localName = "infoBilancioGestAmmRespResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.InfoBilancioGestAmmRespResponse")
    @WebResult(name = "infoBilancioGestAmmRespReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.lang.String infoBilancioGestAmmResp(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestDirezioni", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestDirezioni")
    @ResponseWrapper(localName = "searchGestDirezioniResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestDirezioniResponse")
    @WebResult(name = "searchGestDirezioniReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestDirezioni()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestMateria", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestMateria")
    @ResponseWrapper(localName = "searchGestMateriaResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestMateriaResponse")
    @WebResult(name = "searchGestMateriaReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestMateria()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchComboV2GestClassiADI", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchComboV2GestClassiADI")
    @ResponseWrapper(localName = "searchComboV2GestClassiADIResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchComboV2GestClassiADIResponse")
    @WebResult(name = "searchComboV2GestClassiADIReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchComboV2GestClassiADI(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in2
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestAnnoEser", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAnnoEser")
    @ResponseWrapper(localName = "searchGestAnnoEserResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAnnoEserResponse")
    @WebResult(name = "searchGestAnnoEserReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestAnnoEser(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        javax.xml.datatype.XMLGregorianCalendar in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "testResources", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.TestResources")
    @ResponseWrapper(localName = "testResourcesResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.TestResourcesResponse")
    @WebResult(name = "testResourcesReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public boolean testResources()
 throws CSIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoCodiciATECOSecondoLivello", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoCodiciATECOSecondoLivello")
    @ResponseWrapper(localName = "getElencoCodiciATECOSecondoLivelloResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoCodiciATECOSecondoLivelloResponse")
    @WebResult(name = "getElencoCodiciATECOSecondoLivelloReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoCodiciATECOSecondoLivello()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestModPresentIstanza", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestModPresentIstanza")
    @ResponseWrapper(localName = "searchGestModPresentIstanzaResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestModPresentIstanzaResponse")
    @WebResult(name = "searchGestModPresentIstanzaReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestModPresentIstanza(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestAmmResp", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAmmResp")
    @ResponseWrapper(localName = "searchGestAmmRespResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAmmRespResponse")
    @WebResult(name = "searchGestAmmRespReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestAmmResp(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchAttoApprov", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAttoApprov")
    @ResponseWrapper(localName = "searchAttoApprovResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchAttoApprovResponse")
    @WebResult(name = "searchAttoApprovReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.AttoAmmApprovazioneDto> searchAttoApprov(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        long in1,
        @WebParam(name = "in2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        javax.xml.datatype.XMLGregorianCalendar in2,
        @WebParam(name = "in3", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        long in3,
        @WebParam(name = "in4", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in4
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "verificaCollegamentoImpegno", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.VerificaCollegamentoImpegno")
    @ResponseWrapper(localName = "verificaCollegamentoImpegnoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.VerificaCollegamentoImpegnoResponse")
    @WebResult(name = "verificaCollegamentoImpegnoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.lang.Double verificaCollegamentoImpegno(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Boolean in1,
        @WebParam(name = "in2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Boolean in2
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestAffidamentoV3", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamentoV3")
    @ResponseWrapper(localName = "searchGestAffidamentoV3Response", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamentoV3Response")
    @WebResult(name = "searchGestAffidamentoV3Return", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestAffidamentoV3(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipoAggiudicaz2127", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoAggiudicaz2127")
    @ResponseWrapper(localName = "searchGestTipoAggiudicaz2127Response", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoAggiudicaz2127Response")
    @WebResult(name = "searchGestTipoAggiudicaz2127Return", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipoAggiudicaz2127(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestAffidamentoV2", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamentoV2")
    @ResponseWrapper(localName = "searchGestAffidamentoV2Response", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamentoV2Response")
    @WebResult(name = "searchGestAffidamentoV2Return", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestAffidamentoV2()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoTipiSIEG", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiSIEG")
    @ResponseWrapper(localName = "getElencoTipiSIEGResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiSIEGResponse")
    @WebResult(name = "getElencoTipiSIEGReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoTipiSIEG()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestAffidamento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamento")
    @ResponseWrapper(localName = "searchGestAffidamentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestAffidamentoResponse")
    @WebResult(name = "searchGestAffidamentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestAffidamento()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestProgrammazione", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestProgrammazione")
    @ResponseWrapper(localName = "searchGestProgrammazioneResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestProgrammazioneResponse")
    @WebResult(name = "searchGestProgrammazioneReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestProgrammazione()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDocumento", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetDocumento")
    @ResponseWrapper(localName = "getDocumentoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetDocumentoResponse")
    @WebResult(name = "getDocumentoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public byte[] getDocumento(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1
    ) throws CSIException_Exception, InvalidParameterCommonException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestDirezioniOI", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestDirezioniOI")
    @ResponseWrapper(localName = "searchGestDirezioniOIResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestDirezioniOIResponse")
    @WebResult(name = "searchGestDirezioniOIReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestDirezioniOI()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getElencoTipiStrumentiAiuto", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiStrumentiAiuto")
    @ResponseWrapper(localName = "getElencoTipiStrumentiAiutoResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.GetElencoTipiStrumentiAiutoResponse")
    @WebResult(name = "getElencoTipiStrumentiAiutoReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> getElencoTipiStrumentiAiuto()
 throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipoSportello", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoSportello")
    @ResponseWrapper(localName = "searchGestTipoSportelloResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoSportelloResponse")
    @WebResult(name = "searchGestTipoSportelloReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipoSportello(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestTipoAggiudicaz", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoAggiudicaz")
    @ResponseWrapper(localName = "searchGestTipoAggiudicazResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestTipoAggiudicazResponse")
    @WebResult(name = "searchGestTipoAggiudicazReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestTipoAggiudicaz(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchGestClassiADI", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestClassiADI")
    @ResponseWrapper(localName = "searchGestClassiADIResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchGestClassiADIResponse")
    @WebResult(name = "searchGestClassiADIReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchGestClassiADI(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0
    ) throws CSIException_Exception, UnrecoverableException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchComboGestClassiADI", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchComboGestClassiADI")
    @ResponseWrapper(localName = "searchComboGestClassiADIResponse", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/", className = "it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SearchComboGestClassiADIResponse")
    @WebResult(name = "searchComboGestClassiADIReturn", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
    public java.util.List<it.csi.serse.serseweb.integration.ws.cxf.budgetbilserv.common.SelItemDto> searchComboGestClassiADI(

        @WebParam(name = "in0", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://common.interfacecsi.budgetbilserv.gambudget.csi.it/")
        java.lang.String in1
    ) throws CSIException_Exception, UnrecoverableException_Exception, CommonException_Exception, SystemException_Exception;
}
